/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type GetKeywordsParams = {
  page?: string;
  limit?: string;
  search?: string;
  categoryId?: string;
  natureId?: string;
  novelId?: string;
};
