/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type PostReplacementsBodyOne = {
  /** @minLength 1 */
  replacement: string;
  keywordId: string;
};
